# TODO 配置数据源相关信息

server:
  port: 80


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_2 #?servierTimezone=UTC
#    url: jdbc:mysql://localhost:3306/db_2?serverTimezone=GMT%2b8&amp;useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
  main:
    banner-mode: off
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-wait: 1
        max-idle: 10
        min-idle: 0
      timeout: 1000
    jedis:
      pool:
        max-active: 100
        max-wait: 1
        max-idle: 10
        min-idle: 0
      timeout: 1000
#        max-idle: 16
#        max-active: 32
#        min-idle: 8
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2912027140@qq.com
    password: pyoebgseyolfdeca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB


logging:
  file:
    name: D:/code/demo7/record.log
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off
#
#spring:
#  mvc:
#  servlet:
#    multipart:
#      max-file-size: 10MB  		# 设置单个文件最大大小为10MB
#      max-request-size: 100MB

